### ISSUE TITLE
Clickable users

### ISSUE THREAD

**Issue by Cody-Q** [iyu46/RemovedConnectionAlerts#11]
GuildAndFriendRemovalAlerts used to have a feature where you could click on the user that removed you to open their dm. Been trying to find a way to do it myself, but it's way over my head

**Comment by iyu46** [comment]
Sorry for getting to this so late. I'm not sure that this is reliably possible anymore (or was reliably possible in that plugin either). Since the discriminator usernames are gone (user#1111), any users in your history logged with them currently can't be accessed through that handle, so they'd go nowhere. What's more, if someone changes their username, the link would also go nowhere - there's no way to "track" a person's username changes (and I wouldn't want that in my plugin even if it was possible, since it's a big security and privacy concern).

I'd recommend maybe keeping the person's dm's open, or maybe just using the Quick Switcher (CTRL + T on Windows, otherwise known as the search bar in the top left of the dms screen) and typing in their username to find them?
